RMApp_RMShowHotkey:
RMApp_RMShowHotkey()
return
RMApp_RSMShowHotkey:
return
RMApp_TrayOpenRMFolder:
RMApp_TrayOpenRMFolder()
return
RMApp_TrayMenuRMD:
RMApp_TrayMenuRMD()
return
RMApp_TraySkinAndProfileChanger:
RMApp_TraySkinAndProfileChanger()
return
RMApp_TrayAboutRM:
RMApp_TrayAboutRM()
return
RMApp_TraySuspend:
RMApp_TraySuspend()
return
RMApp_TrayReload:
RMApp_TrayReload()
return
RMApp_TrayExit:
RMApp_TrayExit()
return
RMApp_NavSub:
RMApp_NavSub("RMApp_NavReg")
return
RMApp_UpdatesGuiAHK:
RMApp_UpdatesGuiAHK()
return
RMApp_UpdatesGuiRM:
RMApp_UpdatesGuiRM()
return
RMApp_CheckInternetConnection:
RMApp_CheckInternetConnection()
return
RMApp_MessageReceiverExecute:
RMApp_MessageReceiverExecute()
return
RMApp_ReportGuiGuiSize:
RMApp_ReportGuiGuiSize()
return
RMApp_DoNothing:	
return